name: Application Deploy

on:
  push:
    paths:
      - .github/workflows/deploy.yml
      - apps/**
      - packages/**
      - tests/**
      - infra/tf/app/**
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: choice
        options:
          - dev
        default: dev

jobs:
  deploy:
    uses: rwitzlib/github-action-templates/.github/workflows/dotnet-container-deployment.yml@v1.9.0
    permissions:
      id-token: write
      contents: read
      packages: read
      actions: read
    with:
      environment: ${{ inputs.environment || 'dev' }}
      docker: |
        [
          {
            "ecr_repo": "stockmountain-${{ inputs.environment || 'dev' }}-market-data-aggregator",
            "dockerfile": "apps/market-data-aggregator/Dockerfile",
            "context": ".",
            "build-args": ""
          },
          {
            "ecr_repo": "stockmountain-${{ inputs.environment || 'dev' }}-backtester",
            "dockerfile": "apps/backtester/Dockerfile",
            "context": ".",
            "build-args": ""
          }
        ]
      solution_directory: .
      global_json_file: global.json
      terraform_directory: infra/tf/app
    secrets: inherit