name: Core Deploy

on:
  push:
    paths:
      - .github/workflows/core-deploy.yml
      - infra/tf/core/**
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: choice
        options:
          - dev
        default: dev

jobs:
  deploy:
    uses: rwitzlib/github-action-templates/.github/workflows/terraform-deploy.yml@v1.7.0
    permissions:
      id-token: write
      contents: read
      actions: read
    with:
      environment: ${{ inputs.environment || 'dev' }}
      terraform_directory: infra/tf/core
    secrets: inherit