name: Deploy Market Data Aggregator

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        type: choice
        options:
          - dev
        default: dev

jobs:
  uses: rwitzlib/github-action-templates/.github/workflows/dotnet-container-deployment.yml@1.6.0
  with:
    environment: ${{ github.event.inputs.environment || 'dev' }}
    docker: |
      '[
        {
          "ecr_repo":"stockmountain-${{ github.event.inputs.environment || 'dev' }}-market-data-aggregator",
          "dockerfile":"apps/market-data-aggregator/Dockerfile",
          "context":".",
          "build-args":""
        }
      ]'
    solution_directory: '.'
    global_json_file: 'global.json'
    terraform_directory: 'infra/tf'